weights: ./runs/train/exp16/weights/last.pt
cfg: ''
data: /content/drive/MyDrive/yolov5/data/data.yaml
hyp: data/hyp.scratch.yaml
epochs: 1500
batch_size: 1
img_size:
- 416
- 416
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 8
project: runs/train
name: exp
exist_ok: false
total_batch_size: 1
world_size: 1
global_rank: -1
save_dir: runs/train/exp16
